### ISSUE TITLE
Found broken `/graphql/tools/docs/api/modules/load#loaddocuments` link. Please fix!

### ISSUE THREAD

**Issue by jeffcap1** [the-guild-org/website#1004]
In the [Usage section](https://the-guild.dev/graphql/tools/docs/documents-loading#usage) of the Documents Loading page the API documentation and warning links lead to a 404 page.

<img width="1455" alt="image" src="https://user-images.githubusercontent.com/7104326/209862164-a83ec3e8-1070-4376-a058-263f0ce314ce.png">

**Comment by dotansimha** [comment]
@TuvalSimha can you please help with fixing this one?

**Comment by TuvalSimha** [comment]
Hey @jeffcap1 :),
Thank you for your issue, the links were changed, you can review my changes here: https://github.com/ardatan/graphql-tools/pull/4983.
And of course, you can try to open the links again: https://the-guild.dev/graphql/tools/docs/documents-loading#usage
