### ISSUE TITLE
Found broken `/graphql/yoga-server/examples/graphql-sse` link. Please fix!

### ISSUE THREAD

**Issue by aless10** [the-guild-org/website#1037]
Here => https://the-guild.dev/graphql/yoga-server/docs/features/subscriptions#graphql-over-server-sent-events-protocol-via-graphql-sse
![Screenshot 2023-01-18 alle 15 50 40](https://user-images.githubusercontent.com/19170381/213203310-a53f00c4-dd46-4f09-8b18-d8c00d46ae5c.png)

**Comment by dotansimha** [comment]
Thank you @aless10 ! we'll take care of that soon!
