### ISSUE TITLE
Found broken `/graphql/apollo-angular/docs/data/setup.html#using-dependency-injection` link. Please fix!

### ISSUE THREAD

**Issue by grosch** [the-guild-org/website#1092]

**Comment by dotansimha** [comment]
@TuvalSimha can you please take a look? I guess it's a missing redirect from an old page?

**Comment by TuvalSimha** [comment]
@dotansimha 
This path is good - https://the-guild.dev/graphql/apollo-angular/docs/data/queries#using-dependency-injection
We are not directed page links with HTML like that `/graphql/apollo-angular/docs/data/setup.html#using-dependency-injection`.
