### ISSUE TITLE
Found broken `/graphql/codegen/docs/guides/graphql-cli` link. Please fix!

### ISSUE THREAD

**Issue by paul-vd** [the-guild-org/website#1148]
This is from the search.

![image](https://user-images.githubusercontent.com/39598117/225309148-68afc8cd-8651-4891-9183-22e3647fb248.png)

**Comment by dotansimha** [comment]
I think it's an old page that was not indexing in our search engine. It will probably sync soon. 

On the same matter, `graphql-cli` is not maintained, and we've just pushed a migration guide in order to drop it and migrate the configuration to just using GraphQL Codegen CLI directly, see:

**Comment by paul-vd** [comment]
I was actually searching for more info on `@graphql-codegen/cli`

**Comment by dotansimha** [comment]
> @dotansimha I was actually searching for more info on `@graphql-codegen/cli` to find this [the-guild.dev/graphql/codegen/docs/config-reference/codegen-config#cli-flags](https://the-guild.dev/graphql/codegen/docs/config-reference/codegen-config#cli-flags), but seems you need to:
> 
> * navigate to the installation page: [the-guild.dev/graphql/codegen/docs/getting-started/installation](https://the-guild.dev/graphql/codegen/docs/getting-started/installation)
> * find the link: [codegen.yaml API reference documentation](https://the-guild.dev/graphql/codegen/docs/config-reference/codegen-config).
> * Scroll down to [the-guild.dev/graphql/codegen/docs/config-reference/codegen-config#cli-flags](https://the-guild.dev/graphql/codegen/docs/config-reference/codegen-config#cli-flags)
> 
> Which is quite difficulty, I would expect it to be in the search when searching `cli`

Thank you for the feedback! 

@saihaj maybe we can improve some aspects of the docs?

**Comment by paul-vd** [comment]
I just noticed that the correct doc in the search is the codegen.ts, which is quite hidden, maybe add a subdoc dedicated to the cli? for example Mesh cli is correctly listed in the search

![image](https://user-images.githubusercontent.com/39598117/225529666-fc7a8095-e957-4020-97b6-9d403681a7bb.png)
