### ISSUE TITLE
Found broken `/graphql/hive/features/high-availability-cdn` link. Please fix!

### ISSUE THREAD

**Issue by rh-danderson** [the-guild-org/website#1170]

**Comment by rh-danderson** [comment]
They're all around https://the-guild.dev/graphql/hive/docs/get-started/apollo-federation

**Comment by dotansimha** [comment]
thanks @rh-danderson , we had a broken deployment. should be fixed in a few minutes.

**Comment by dotansimha** [comment]
fixed ✅
