### ISSUE TITLE
Found broken `/graphql/apollo-angular/v1/performance/improving-performance` link. Please fix!

### ISSUE THREAD

**Issue by skog-newglue** [the-guild-org/website#1313]
Found on https://the-guild.dev/graphql/apollo-angular/docs

**Comment by TuvalSimha** [comment]
Hey @skog-newglue,
You can review my changes [here](https://github.com/kamilkisiela/apollo-angular/pull/2058), and of course, you are more then welcome to try use the page again.
Thank you!
