### ISSUE TITLE
Found broken `/graphql/inspector/docs/essentials/diff` link. Please fix!

### ISSUE THREAD

**Issue by glg-satish-tripathi** [the-guild-org/website#1326]
I am trying to read more about it but the link is broken from the below log:
https://medium.com/the-guild/graphql-inspector-481c1a5ef616
[Finds breaking, dangerous and safe changes](https://graphql-inspector.com/docs/essentials/diff) when modifying a

**Comment by TuvalSimha** [comment]
Hey @glg-satish-tripathi,
Thank you for this super important issue, you are more than welcome to try again the links. 
Also, you can review the changes i did to fix this issue - [LINK](https://github.com/kamilkisiela/graphql-inspector/pull/2583)

**Comment by glg-satish-tripathi** [comment]
Thank you @TuvalSimha for fixing it. it works now.
