### ISSUE TITLE
Found broken `/graphql/apollo-angular/docs/data/setup` link. Please fix!

### ISSUE THREAD

**Issue by AlouaniHabib** [the-guild-org/website#1330]

**Comment by TuvalSimha** [comment]
Hey @AlouaniHabib,
Thank you for this issue.
Can you mention where did you find this broken path?
We have this `setup`([link](https://the-guild.dev/graphql/apollo-angular/v1/basics/setup)) path in `V1` and for docs we dont have `setup` path.

**Comment by TuvalSimha** [comment]
Hey @AlouaniHabib,
i understand the issue, just fixed the redirects, you can see the changes [here](https://github.com/kamilkisiela/apollo-angular/pull/2058).
Thank you.
