### ISSUE TITLE
Found broken `/graphql/inspector/products/action` link. Please fix!

### ISSUE THREAD

**Issue by alex-the** [the-guild-org/website#1331]

**Comment by TuvalSimha** [comment]
Hey @alex-the,
Thank you for this issue.
You talked about this route? https://the-guild.dev/graphql/inspector/docs/products/action

**Comment by alex-the** [comment]
Looks fixed! I was clicking about in the docs and was getting a lot of too many redirects and a 404 there (I think). But I'm not having the same issues now.
