### ISSUE TITLE
Found broken `/graphql/inspector/products/action` link.

### ISSUE THREAD

**Issue by seth-acuitymd** [the-guild-org/website#1338]
Clicking the link
> "Follow the installation instructions provided in the ["GitHub Action"](https://the-guild.dev/graphql/inspector/products/action) chapter." 

from page - https://the-guild.dev/graphql/inspector/docs/installation - 

![Screenshot 2023-07-14 at 2 25 21 PM](https://github.com/the-guild-org/website/assets/117682158/ad9e6edc-7f82-4469-8cf3-d3fa9d869b65)

Leads to a 404 - 
![Screenshot 2023-07-14 at 2 26 48 PM](https://github.com/the-guild-org/website/assets/117682158/2af727f6-a4f2-4392-b2bb-988a8930ba26)

I _think_ it's supposed to target - https://the-guild.dev/graphql/inspector/docs/products/action ?

**Comment by TuvalSimha** [comment]
Hey @seth-acuitymd,
Thank you for this issue, you are more than welcome to explore the website docs - [LINK](https://the-guild.dev/graphql/inspector/docs/installation), and the changes i did - [LINK](https://github.com/kamilkisiela/graphql-inspector/pull/2582).
