### ISSUE TITLE
Found broken `/graphql/inspector/docs/essentials/audit` link. Please fix!

### ISSUE THREAD

**Issue by stephen-barrow** [the-guild-org/website#1526]
https://the-guild.dev/graphql/mesh/docs/plugins/max-tokens
Learn more about graphql-inspector audit [here](https://the-guild.dev/graphql/inspector/docs/essentials/audit).

**Comment by TuvalSimha** [comment]
Hey @stephen-barrow 
Thank you for this new issue, the route fixed :)
https://github.com/kamilkisiela/graphql-inspector/pull/2691
