### ISSUE TITLE
Found broken `/graphql/hive/docs/features/sso-oidc-provider` link. Please fix!

### ISSUE THREAD

**Issue by ispayde** [the-guild-org/website#1536]
Hello, 

This link is broken and I'm trying to setup SSO for my organization. Thanks.

**Comment by YassinEldeeb** [comment]
Hey! The documentation for SSO can be found here https://the-guild.dev/graphql/hive/docs/management/sso-oidc-provider

There might have been a misdirection in a blog post, can you please tell us where did you found that broken link so we can update it?

**Comment by TuvalSimha** [comment]
Hey @ispayde,
not sure from where you found this link, but i created a redirect to the right path, you can check out the related solutions here: https://github.com/kamilkisiela/graphql-hive/pull/4531.
