### ISSUE TITLE
Found broken `/graphql/hive/docs/features/registry-usage%22%7D` link. Please fix!

### ISSUE THREAD

**Issue by cassidycodes** [the-guild-org/website#1537]
This link shows up using the Hive CLI `hive artifact:fetch`

**Comment by TuvalSimha** [comment]
Hey @cassidycodes,
thanks for this new issue.
can you share more information about it? not sure where you get 404. on this section? https://the-guild.dev/graphql/hive/docs/api-reference/cli#fetch-a-schema-from-cdn

**Comment by cassidycodes** [comment]
@TuvalSimha This link shows up when I use the hive cli. Unfurling the URI escaped path shows that there is likely an error in how the hive CLI presents the URL. The unescaped URL has extra characters: `/graphql/hive/docs/features/registry-usage"}`
