### ISSUE TITLE
Found broken `/graphql/mesh/v1/serve/features/health-check` link. Please fix!

### ISSUE THREAD

**Issue by wenn** [the-guild-org/website#1737]

**Comment by ardatan** [comment]
Fixed!
https://github.com/ardatan/graphql-mesh/commit/9f01438fbdf327c0a4bfa0cf440d890ec871ffcc#diff-bb105bb11c37c93cf091a1adeaedc7f7b78940500ef75dcf6dd2bf42c5bf9ce0R453
