### ISSUE TITLE
Feedback for “Unleash the power of Fragments with GraphQL Codegen”

### ISSUE THREAD

**Issue by cacieprins** [the-guild-org/website#858]
Can you include examples on how to set up mock properties for unit testing components that rely on fragments? The patterns I'm coming up with are brutally complex, and the `graphql-codegen-typescript-mock-data` plugin doesn't create mocks for fragments. I may be missing something very straightforward, but I can't find any documentation on how to easily mock out fragments when using the types generated by this tool.

for example, a simple component and a simple fragment:

```typescript
// component
export const BirthdayNote_User = graphql(`
  fragment BirthdayNote_User on User {
    id
    birthdate
  }
`);

const BirthdayNote: React.FC<{ user: FragmentType<typeof BirthdayNote_User> }> = (props) => { ...etc }
```
result on this extraordinarily convoluted setup for a mock property:

```typescript
const baseUser: Pick<User, 'id' | 'birthdate'> = { // because it's fragment data, and other User fields are required for the User type
  id: '1234',
  birthdate: 'Oct 3 2002'
}
const userProp: FragmentType<typeof BirthdayNote_UserFragment> = {
  ...baseUser, // this is the data that will actually be used by the component after running through `useFragment`, which just seems to return the second parameter as is anyways
  ' $fragmentRefs': { // this is necessary to fulfill the `FragmentType` type definition on the property
    BirthdayNote_UserFragment: {
      ...baseUser,
      ' $fragmentName': 'BirthdayNote_UserFragment'
    }
};

it('renders the birthday', () => {
  render(<BirthdayNote user={userProp} />);
  // some assertions here
});
```

**Comment by n1ru4l** [comment]
Does this work for you? https://the-guild.dev/graphql/codegen/plugins/presets/preset-client#fragment-masking-and-testing
