### ISSUE TITLE
Found broken `/graphql/tools/docs/api/modules/merge#mergetypedefs` link. Please fix!

### ISSUE THREAD

**Issue by vchernev8** [the-guild-org/website#946]

**Comment by dotansimha** [comment]
@TuvalSimha can you please take a look? I guess just a missing redirect from an old path?

**Comment by TuvalSimha** [comment]
Hey @vchernev8,
You are more than welcome to try again - [LINK](https://the-guild.dev/graphql/tools/docs/api/modules/merge#mergetypedefs) :)
I added a new redirect path, you can see it here: https://github.com/ardatan/graphql-tools/pull/4860

Thank you!
