### ISSUE TITLE
Found broken `/privacy-policy.pdf` link. Please fix!

### ISSUE THREAD

**Issue by Ceres6** [the-guild-org/website#996]

**Comment by Ceres6** [comment]
Hi, It's found on https://the-guild.dev/graphql/hive on the bottom on the cookies banner in the "Privacy Policy" link. 

Besides there should be a button for rejecting cookies as it should be possible to do so in the same number of "clicks" as accepting them. 

The message "This website uses cookies to analyze site usage and improve your experience.
If you continue to use our services, you are agreeing to the use of such cookies." that appears in that banner is no longer valid as sites shouldn't load any cookies prior to user acceptance. That also means the page shouldn't load them as it's actually doing.

**Comment by dotansimha** [comment]
@kamilkisiela can we improve the cookie banner setup?
